### ISSUE TITLE
S3 bucket is created for app instances always

### ISSUE THREAD

**Issue by coltoneshaw** [mattermost/mattermost-load-test-ng#555] opened 2023-02-08 20:36 UTC
We have a customer who cannot create S3 buckets via terraform, so they've manually created them and we have a patch file with the S3 bucket getting pushed into Mattermost. We'd like to skip this step via the config. 

https://github.com/mattermost/mattermost-load-test-ng/blob/14168ff28c541c76a6afa03856c904a4aefe14ed/deployment/terraform/assets/cluster.tf#L233-L234

**Comment by agnivade** [comment] 2023-02-09 07:40
I want to understand this better and see if there's a better solution here. So the customer can create everything else but _not_ the S3 bucket? If you are using a patch file with the S3 bucket, that means you are using a bucket anyways right? Or is there a technical problem with creating S3 buckets?

If the problem is that a customer wants to use a pre-loaded S3 bucket, they can do so by using https://github.com/mattermost/mattermost-load-test-ng/blob/master/docs/deployer_config.md#s3bucketdumpuri.

**Comment by agarciamontoro** [comment] 2023-07-14 15:49
Gentle ping on this, @coltoneshaw. What's the current status of this issue?

**Comment by streamer45** [comment] 2023-08-04 02:44
@agnivade Would https://github.com/mattermost/mattermost-load-test-ng/pull/636 be sufficient to close this one?

**Comment by agnivade** [comment] 2023-08-04 02:45
Yep

**Closed by agnivade** 2023-08-04 02:45 UTC
